services:
  grafana:
    image: grafana/grafana:11.5.2
    ports:
      - "${PORT}:3000"
    environment:
      - GF_USERS_DEFAULT_THEME=${USERS_DEFAULT_THEME}
      - GF_LOG_MODE=${LOG_MODE}
      - GF_LOG_LEVEL=${LOG_LEVEL}
      - GF_AUTH_GENERIC_OAUTH_ENABLED=${AUTH_GENERIC_OAUTH_ENABLED}
      - GF_AUTH_GENERIC_OAUTH_NAME=${AUTH_GENERIC_OAUTH_NAME}
      - GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP=${AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP}
      - GF_AUTH_GENERIC_OAUTH_AUTO_LOGIN=${AUTH_GENERIC_OAUTH_AUTO_LOGIN}
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=${AUTH_GENERIC_OAUTH_CLIENT_ID}
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=${AUTH_GENERIC_OAUTH_CLIENT_SECRET}
      - GF_AUTH_GENERIC_OAUTH_SCOPES=${AUTH_GENERIC_OAUTH_SCOPES}
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=${AUTH_GENERIC_OAUTH_AUTH_URL}
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=${AUTH_GENERIC_OAUTH_TOKEN_URL}
      - GF_AUTH_GENERIC_OAUTH_API_URL=${AUTH_GENERIC_OAUTH_API_URL}
      - GF_AUTH_GENERIC_OAUTH_SIGNOUT_REDIRECT_URL=${AUTH_GENERIC_OAUTH_SIGNOUT_REDIRECT_URL}
      - GF_AUTH_GENERIC_OAUTH_USE_REFRESH_TOKEN=${AUTH_GENERIC_OAUTH_USE_REFRESH_TOKEN}
      - GF_AUTH_GENERIC_OAUTH_TLS_SKIP_VERIFY_INSECURE=${AUTH_GENERIC_OAUTH_TLS_SKIP_VERIFY_INSECURE}
      - GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH=${AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH}
      - GF_AUTH_GENERIC_OAUTH_ALLOW_ASSIGN_GRAFANA_ADMIN=${AUTH_GENERIC_OAUTH_ALLOW_ASSIGN_GRAFANA_ADMIN}
    volumes:
      - data:/var/lib/grafana

volumes:
  data:
    external: false
